version: "3"
services:
  express:
    container_name: cop4331-express
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    container_name: cop4331-mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-express:
    container_name: cop4331-mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
