name: Deploy to Lambda

# On push to the backend folder, Pull Requests, or main branch
on:
  push:
    paths:
      - "backend/**"
    branches:
      - main
  pull_request:
    paths:
      - "backend/**"
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Build Express.js project
        run: cd backend && npm install && npm run build && zip -r backend.zip dist && mv backend.zip ../

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        run: aws lambda update-function-code --function-name cop4331-express-lambda --zip-file fileb://backend.zip --revision-id ${{ github.ref }}
