name: Frontend Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build_and_deploy_frontend_main:
    if: ${{ github.event_name == 'push' }}
    name: Build and Deploy React to AWS Amplify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Deploy
        run: |
          cd frontend
          npm install -g @aws-amplify/cli
          amplify configure
          amplify publish

  build_and_deploy_frontend_pr:
    if: ${{ github.event_name == 'pull_request' }}
    name: Build and Deploy React to AWS Amplify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Amplify
        id: deploy
        run: aws amplify start-job --app-id ${{ secrets.AMPLIFY_APP_ID }} --branch-name ${{ github.event.pull_request.head.ref }} --job-type RELEASE
